name: tectup-tour

include:
  - ./compose/proxy.compose.yml
  - ./compose/db.compose.yml
  - ./compose/spark.compose.yml
  - ./compose/kestra.compose.yml
  - ./compose/minio.compose.yml

volumes:
  minio-vol:
    name: minio-vol
    driver: local


networks:
  etl-net:
    external: true
