services:
  kestra-minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    entrypoint:
      - sh
      - -c
    command:
      - mkdir -p /data/kestra && minio server /data --address ":9000"
    networks:
      - etl-net
    deploy:
      resources:
        limits:
          memory: 300Mb
          cpus: 0.3
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - kestra-minio-vol:/data:rw
      # - ./app/scripts:/data/kestra/namespaces/demo/_files:rw

  kestra-db:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - kestra-db-vol:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 300Mb
          cpus: 0.3
    networks:
      - etl-net
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra_password
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -d kestra -U kestra'
      interval: 30s
      timeout: 10s
      retries: 10

  kestra-web:
    depends_on:
      kestra-db:
        condition: service_started
      kestra-minio:
        condition: service_started

    image: kestra/kestra:latest-lts
    restart: unless-stopped
    command: server standalone --config /etc/kestra/config.yaml
    user: "root"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024Mb
          cpus: 0.6
    environment:
      KESTRA_URL: http://localhost:8080/
      DOCKER_HOST: tcp://docker-proxy:2375
      KESTRA_PLUGINS_CONFIGURATIONS_0_VALUES_HOST: tcp://docker-proxy:2375
    networks:
      - etl-net
    ports:
      - 8080:8080
    configs:
      - source: kestra_yaml
        target: /etc/kestra/config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/flows:/usr/app/local_flows:rw
      - ./app/scripts:/usr/app/scripts:rw



# for prod, creds should not set in plain, maybe by env

configs:
  kestra_yaml:
    content: |
      datasources:
        postgres:
          driverClassName: org.postgresql.Driver
          url: jdbc:postgresql://kestra-db:5432/kestra
          username: kestra
          password: kestra_password


      kestra:

        tutorial-flows:
          enabled: false
        blueprints:
          enabled: false
        jdbc:
          queues:
          messageProtection:
            enabled: true
            limit: 1048576
        encryption:
          secret-key: 50ee98d2e259b314151c51663580aa62cebb8590ba98db336e9ccdb4c972502a

        server:
          basicAuth:
            enabled: true
            username: admin@local.host
            password: Password123!
        url: http://localhost:8080
        repository:
          type: postgres
        storage:
          type: minio
          minio:
            endpoint: http://kestra-minio
            port: 9000
            accessKey: minio
            secretKey: minio_password
            bucket: kestra
            region: us-east-1
        queue:
          type: postgres
        tasks:
          tmpDir:
            path: "/tmp/kestra-wd/tmp"
        plugins:
          configurations:
            - type: io.kestra.plugin.scripts.runner.docker.Docker
              values:
                network: etl-net
                volume-enabled: true
      micronaut:
        io:
          watch:
            enabled: true
            paths:
              - /usr/app/local_flows


volumes:
  kestra-db-vol:
    name: kestra-db-vol
    driver: local

  kestra-minio-vol:
    name: kestra-minio-vol
    driver: local
