services:
  kestra-minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    entrypoint:
      - sh
      - -c
    command:
      - mkdir -p /data/kestra && minio server /data --address ":9000"
    networks:
      - etl-net
    deploy:
      resources:
        limits:
          memory: 300Mb
          cpus: 0.3
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - kestra-minio-vol:/data:rw

  kestra-db:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - kestra-db-vol:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 300Mb
          cpus: 0.3
    networks:
      - etl-net
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra_password
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -d kestra -U kestra'
      interval: 30s
      timeout: 10s
      retries: 10

  kestra-web:
    depends_on:
      kestra-db:
        condition: service_started
      kestra-minio:
        condition: service_started

    image: kestra/kestra:latest-lts
    restart: unless-stopped
    command: server standalone --config /etc/kestra/config.yaml
    user: "root"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024Mb
          cpus: 0.6
    environment:
      KESTRA_URL: http://localhost:8080/
      # DOCKER_HOST: tcp://docker-proxy:2375
      KESTRA_PLUGINS_CONFIGURATIONS_0_VALUES_HOST: tcp://docker-proxy:2375
      KESTRA_SERVER_BASIC_AUTH_USERNAME: admin@local.host
      KESTRA_SERVER_BASIC_AUTH_PASSWORD: Password123!
      KESTRA_ENCRYPTION_SECRET_KEY: 50ee98d2e259b314151c51663580aa62cebb8590ba98db336e9ccdb4c972502a
      KESTRA_STORAGE_MINIO_ACCESS_KEY: minio
      KESTRA_STORAGE_MINIO_SECRET_KEY: minio_password
    networks:
      - etl-net
    ports:
      - 8080:8080
    configs:
      - source: kestra_yaml
        target: /etc/kestra/config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/flows:/usr/app/local_flows:rw
      - ./app/scripts:/usr/app/scripts:rw



configs:
  kestra_yaml:
    file: ./kestra.yaml


volumes:
  kestra-db-vol:
    name: kestra-db-vol
    driver: local

  kestra-minio-vol:
    name: kestra-minio-vol
    driver: local
