services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioa
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "30091:9001"
    volumes:
      - minio-vol:/data
    networks:
      etl-net: