services:
  spark:
    image:  spark:4.0.1-python3
    restart: unless-stopped
    hostname: spark
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark --port 7077 --webui-port 8080
    networks:
      airflow-net:
    ports:
      - "30081:8080" 

  spark-worker-1:
    image:  spark:4.0.1-python3
    restart: unless-stopped
    depends_on:
      - spark
    networks:
      airflow-net:
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark:7077

  spark-worker-2:
    image:  spark:4.0.1-python3
    restart: unless-stopped
    depends_on:
      - spark
    networks:
      airflow-net:
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark:7077