id: etl_pipeline
namespace: dev
description: "An ETL pipeline that fetches data from public APIs, processes it with Spark, and stores the result in MinIO."
triggers:
  - id: daily_midnight_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 0 * * *" # Runs every day at 00:00:00 UTC
    withSeconds: true
    timezone: "UTC"
tasks:
  - id: fetch_cat_fact
    type: io.kestra.plugin.core.http.Download
    uri: https://catfact.ninja/fact
    headers:
      accept: "application/json"

  - id: fetch_random_joke
    type: io.kestra.plugin.core.http.Download
    uri: https://v2.jokeapi.dev/joke/Any?type=single
    headers:
      accept: "application/json"


  # - id: process_api_data_with_spark
  #   type: io.kestra.plugin.spark.PythonSubmit
  #   master: spark://spark:7077
  #   deployMode: "CLIENT"
  #   mainScript: ""
  #   taskRunner: 
  #     type: io.kestra.plugin.scripts.runner.docker.Docker
  #     image: "apache/spark:3.5.1-java17-r"
  #     user: root
  #     networkMode: "host"
  #     volumes:
  #       - "/usr/app:/usr/app:rw"

  - id: create_minio_bucket
    type: io.kestra.plugin.minio.CreateBucket
    endpoint: http://minio:9000 
    region: "us-east-1"
    secretKeyId: "minio_password"
    accessKeyId: "minio"
    bucket: "etl"
  # - id: upload_processed_data_to_minio
  #   type: io.kestra.plugin.minio.Upload






